CREATE TABLE public.user_contacts (
    user_id bigint NOT NULL,
    contact_value character varying(255),
    contact_type character varying(255) NOT NULL
);
CREATE TABLE public.user_tags (
    user_id bigint NOT NULL,
    tag_name character varying(255)
);
CREATE TABLE public.users (
    id bigint NOT NULL,
    avatar_url character varying(255),
    description character varying(255),
    email character varying(255) NOT NULL,
    enabled boolean NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    verification_code character varying(255),
    verification_code_expires_at timestamp(6) without time zone,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);
ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);
ALTER TABLE ONLY public.user_contacts
    ADD CONSTRAINT user_contacts_pkey PRIMARY KEY (user_id, contact_type);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.user_tags
    ADD CONSTRAINT fkdylhtw3qjb2nj40xp50b0p495 FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.user_contacts
    ADD CONSTRAINT fkqgbpf3rh5b6i7npvr2rf776rd FOREIGN KEY (user_id) REFERENCES public.users(id);
