CREATE TABLE public.event_registrations (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    event_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    user_id bigint NOT NULL,
    checked_in_at timestamp(6) without time zone,
    code character varying(16),
    answers jsonb,
    CONSTRAINT event_registrations_status_check CHECK (((status)::text = ANY ((ARRAY['REGISTERED'::character varying, 'WAITLISTED'::character varying, 'PENDING'::character varying, 'CANCELLED'::character varying, 'ATTENDED'::character varying])::text[])))
);
ALTER TABLE public.event_registrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_registrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.event_registrations
    ADD CONSTRAINT event_registrations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.event_registrations
    ADD CONSTRAINT uka7lmtg85kt6qxgn51kl82l3qs UNIQUE (code);
ALTER TABLE ONLY public.event_registrations
    ADD CONSTRAINT ukmv1wttabjpboyulu2pql4koqo UNIQUE (user_id, event_id);
