CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_email_sent boolean,
    message character varying(1000) NOT NULL,
    is_read boolean NOT NULL,
    read_at timestamp(6) without time zone,
    related_event_id bigint,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_email character varying(255),
    user_id bigint NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['EVENT_CREATED'::character varying, 'EVENT_UPDATED'::character varying, 'EVENT_LIKED'::character varying, 'EVENT_REMINDER'::character varying, 'REGISTRATION_CONFIRMED'::character varying, 'EVENT_REQUEST_APPROVED'::character varying, 'EVENT_REQUEST_REJECTED'::character varying, 'SUPPORT_RESOLVED'::character varying, 'USER_REGISTERED'::character varying, 'RECOMMENDATION'::character varying])::text[])))
);
ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
