server:
  port: 8085

spring:
  application:
    name: search-service

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    listener:
      type: batch
    consumer:
      group-id: search-service-group-v3
      auto-offset-reset: earliest
      max-poll-records: 500
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: org.ngcvfb.eventhubkz.common.events.EventCreatedEvent

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  metrics:
    distribution:
      percentiles-histogram:
        all: true
      slo:
        all: 50ms, 100ms, 250ms, 500ms, 1s, 2s
    tags:
      application: ${spring.application.name}

logging:
  level:
    org.ngcvfb.searchservice: DEBUG
    org.springframework.kafka: INFO
    org.elasticsearch: INFO
