CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    action character varying(32) NOT NULL,
    actor_id bigint,
    actor_name character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    dedup_key character varying(128) NOT NULL,
    details character varying(2000),
    occurred_at timestamp(6) without time zone NOT NULL,
    target_id bigint,
    target_label character varying(255),
    target_type character varying(16),
    CONSTRAINT audit_log_action_check CHECK (((action)::text = ANY ((ARRAY['USER_REGISTERED'::character varying, 'USER_DELETED'::character varying, 'EVENT_CREATED'::character varying, 'EVENT_UPDATED'::character varying, 'EVENT_DELETED'::character varying, 'EVENT_LIKED'::character varying, 'EVENT_RSVP'::character varying, 'REQUEST_CREATED'::character varying, 'REQUEST_APPROVED'::character varying, 'REQUEST_REJECTED'::character varying])::text[]))),
    CONSTRAINT audit_log_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['USER'::character varying, 'EVENT'::character varying, 'REQUEST'::character varying])::text[])))
);
ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT ukdql0x6kmv7sp86xypf5gk85ox UNIQUE (dedup_key);
CREATE INDEX idx_audit_action ON public.audit_log USING btree (action);
CREATE INDEX idx_audit_actor ON public.audit_log USING btree (actor_id);
CREATE INDEX idx_audit_occurred_at ON public.audit_log USING btree (occurred_at);
