CREATE TABLE public.event_likes (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    event_id bigint NOT NULL,
    user_id bigint NOT NULL
);
ALTER TABLE public.event_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.event_likes
    ADD CONSTRAINT event_likes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.event_likes
    ADD CONSTRAINT ukifn2nr5b5505h6ttu90kggm6v UNIQUE (user_id, event_id);
