CREATE TABLE public.event_request_tags (
    request_id bigint NOT NULL,
    tag_name character varying(255)
);
CREATE TABLE public.event_requests (
    id bigint NOT NULL,
    admin_comment character varying(1000),
    created_at timestamp(6) without time zone,
    event_date timestamp(6) without time zone NOT NULL,
    external_link character varying(255),
    full_description text NOT NULL,
    location character varying(200) NOT NULL,
    main_image_url character varying(1024),
    online boolean NOT NULL,
    registration_deadline timestamp(6) without time zone,
    requester_email character varying(255),
    requester_id bigint,
    reviewed_at timestamp(6) without time zone,
    reviewer_id bigint,
    short_description character varying(500) NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(200) NOT NULL,
    contact_email character varying(255),
    questions jsonb,
    registration_type character varying(255),
    source_channel character varying(200),
    source_url character varying(500),
    source character varying(16) NOT NULL,
    CONSTRAINT event_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);
ALTER TABLE public.event_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.event_staff (
    event_id bigint NOT NULL,
    user_id bigint
);
CREATE TABLE public.event_tags (
    event_id bigint NOT NULL,
    tag_name character varying(255)
);
CREATE TABLE public.events (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    event_date timestamp(6) without time zone NOT NULL,
    external_link character varying(255),
    full_description text NOT NULL,
    like_count integer,
    location character varying(255) NOT NULL,
    main_image_url character varying(1024),
    online boolean NOT NULL,
    organizer_email character varying(255),
    organizer_id bigint NOT NULL,
    registration_deadline timestamp(6) without time zone,
    short_description character varying(500) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    view_count integer,
    registration_type character varying(20),
    questions jsonb,
    CONSTRAINT events_registration_type_check CHECK (((registration_type)::text = ANY ((ARRAY['NATIVE'::character varying, 'EXTERNAL'::character varying, 'NONE'::character varying])::text[])))
);
ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.support_messages (
    id bigint NOT NULL,
    admin_reply text,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    message text NOT NULL,
    name character varying(255) NOT NULL,
    resolved boolean NOT NULL,
    resolved_at timestamp(6) without time zone,
    user_id bigint
);
ALTER TABLE public.support_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.support_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.tags (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(255) NOT NULL
);
ALTER TABLE public.tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.event_requests
    ADD CONSTRAINT event_requests_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.support_messages
    ADD CONSTRAINT support_messages_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_name_type_unique UNIQUE (name, type);
ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tags
    ADD CONSTRAINT ukk6ddd8lmrvnfsx9saefcbaluo UNIQUE (name, type);
ALTER TABLE ONLY public.event_staff
    ADD CONSTRAINT fkcx5y53tbd63eh8afafjecpq79 FOREIGN KEY (event_id) REFERENCES public.events(id);
ALTER TABLE ONLY public.event_request_tags
    ADD CONSTRAINT fkg6tncrcwodfp57qow13hu9ge8 FOREIGN KEY (request_id) REFERENCES public.event_requests(id);
ALTER TABLE ONLY public.event_tags
    ADD CONSTRAINT fkiwoyitw224ykom58m5xnoa9y6 FOREIGN KEY (event_id) REFERENCES public.events(id);
